from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        w = 972
        h = 600
        MainWindow.resize(w, h)
        MainWindow.setFocusPolicy(QtCore.Qt.WheelFocus)

        font16 = QtGui.QFont()
        font16.setPixelSize(16)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(self.centralwidget)
        ww = 430
        self.label.setGeometry(QtCore.QRect((w-ww)//2, 20, ww, 50))
        print((w-ww)//2, ww)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPixelSize(32)
        font.setUnderline(True)
        font.setLetterSpacing(QtGui.QFont.AbsoluteSpacing, 3)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        ww = 300
        self.comboBox.setGeometry(QtCore.QRect((w-ww)//2, 110, ww, 30))
        self.comboBox.setFont(font16)
        self.comboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setEnabled(True)
        ww = 250
        self.lineEdit.setGeometry(QtCore.QRect((w-ww)//2, 160, ww, 30))
        self.lineEdit.setFont(font16)
        self.lineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit.setAcceptDrops(True)
        self.lineEdit.setStyleSheet("border: 1px solid black")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")

        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect((w-ww)//2, 200, ww, 30))
        self.lineEdit_2.setFont(font16)
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_2.setStyleSheet("border: 1px solid black")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setClearButtonEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect((w-ww)//2, 250, ww, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPixelSize(16)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")

        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect((w-ww)//2, 290, ww, 20))
        font = QtGui.QFont()
        font.setPixelSize(16)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")

        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect((w-ww)//2, 320, ww, 20))
        font = QtGui.QFont()
        font.setPixelSize(16)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect((w-ww)//2, 345, ww+10, 70))
        font = QtGui.QFont()
        font.setPixelSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect((w-ww)//2, 470, ww+20, 20))
        font = QtGui.QFont()
        font.setPixelSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect((w-ww)//2, 495, ww, 20))
        font = QtGui.QFont()
        font.setPixelSize(16)
        self.dateEdit.setFont(font)
        self.dateEdit.setObjectName("dateEdit")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect((w-ww)//2, 540, ww, 40))
        font = QtGui.QFont()
        font.setPixelSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background:rgb(49, 45, 32);color:rgb(255,255,255);")
        self.pushButton.setObjectName("pushButton")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 160, 561, 261))
        font = QtGui.QFont()
        font.setPixelSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(410, 150, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPixelSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(440, 200, 101, 21))
        font = QtGui.QFont()
        font.setPixelSize(16)
        self.spinBox.setFont(font)
        self.spinBox.setObjectName("spinBox")

        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(420, 240, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPixelSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setGeometry(QtCore.QRect(440, 280, 101, 22))
        font = QtGui.QFont()
        font.setPixelSize(16)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setObjectName("spinBox_2")

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        ww = 160
        self.pushButton_2.setGeometry(QtCore.QRect((w-ww)//2, 420, ww, 31))
        font = QtGui.QFont()
        font.setPixelSize(15)
        self.pushButton_2.setFont(font)
        # self.pushButton_2.setStyleSheet("background:rgb(49, 45, 32);color:rgb(255,255,255); border: 1px solid cyan")
        self.pushButton_2.setObjectName("pushButton_2")

        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(470, 590, 191, 51))
        font = QtGui.QFont()
        font.setPixelSize(19)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgb(255, 0, 0)")
        self.label_7.setObjectName("label_7")

        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(410, 210, 191, 71))
        font = QtGui.QFont()
        font.setPixelSize(19)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background:rgb(49, 45, 32);color:rgb(255,255,255);")
        self.pushButton_3.setObjectName("pushButton_3")

        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(410, 330, 191, 71))
        font = QtGui.QFont()
        font.setPixelSize(19)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background:rgb(49, 45, 32);color:rgb(255,255,255);")
        self.pushButton_4.setObjectName("pushButton_4")

        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(410, 460, 191, 71))
        font = QtGui.QFont()
        font.setPixelSize(19)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background:rgb(49, 45, 32);color:rgb(255,255,255);")
        self.pushButton_5.setObjectName("pushButton_5")

        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(430, 480, 161, 31))
        font = QtGui.QFont()
        font.setPixelSize(15)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background:rgb(49, 45, 32);color:rgb(255,255,255);")
        self.pushButton_6.setObjectName("pushButton_6")

        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(890, 10, 75, 41))
        font = QtGui.QFont()
        font.setPixelSize(16)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background:rgb(225, 206, 147)")
        self.pushButton_7.setObjectName("pushButton_7")

        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(360, 160, 291, 21))
        font = QtGui.QFont()
        font.setPixelSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 972, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Генерирование пропусков"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:27px;\">Генерирование\n"
"                        пропусков</span></p></body></html>\n"
"                    "))
        self.comboBox.setCurrentText(_translate("MainWindow", "Одному человеку"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Одному человеку"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Нескольким людям"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Посетителям"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Фамилия"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Имя"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Обучающийся"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Слушатель ПК"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Участник мероприятия"))
        self.radioButton.setText(_translate("MainWindow", "Проживает в общежитии"))
        self.radioButton_2.setText(_translate("MainWindow", "Не проживает в общежитии"))
        self.label_2.setText(_translate("MainWindow", "Выберите файл с фотографией\n(jpg, 3:4, ширина не менее 300px)"))
        self.label_3.setText(_translate("MainWindow", "Окончание срока действия пропуска"))
        self.pushButton.setText(_translate("MainWindow", "Сгенерировать пропуск"))
        self.label_4.setText(_translate("MainWindow", "Инфа о входных данных(будет позже)"))
        self.label_5.setText(_translate("MainWindow", "Количество пропусков"))
        self.label_6.setText(_translate("MainWindow", "Начальный номер"))
        self.pushButton_2.setText(_translate("MainWindow", "Выбрать фото"))
        self.label_7.setText(_translate("MainWindow", "Успешно"))
        self.pushButton_3.setText(_translate("MainWindow", "При помощи txt"))
        self.pushButton_4.setText(_translate("MainWindow", "При помощи csv"))
        self.pushButton_5.setText(_translate("MainWindow", "Таблицей\nвнутри приложения"))
        self.pushButton_6.setText(_translate("MainWindow", "Выбрать файл"))
        self.pushButton_7.setText(_translate("MainWindow", "Назад ⇽"))
        self.label_8.setText(_translate("MainWindow", "Информация о входных данных"))
